### ISSUE TITLE
Publish SNAPSHOTs to jCenter.

### ISSUE THREAD

**Issue by dougborg** [srs/gradle-node-plugin#36]
Hey @srs, I think we chatted about this a while back, but it would be great to get SNAPSHOTs for this project and the grunt/gulp plugins published to jCenter.

I just set this up for the https://github.com/ReadyTalk/gradle-readytalk-js project just a few days ago, so you can look at that as an example if you want. I just had to install the travis gem and encrypt my username and api_key for bintray in the travis.yaml file:

```
gradle-node-plugin $ travis encrypt --add BINTRAY_USER=srs
gradle-node-plugin $ travis encrypt --add BINTRAY_KEY=srs_aPi_KeY
```

I just use the env variables directly in my build.gradle instead of passing them as properties, but setting properties with the env variables would work too:

``` yaml
language: groovy

jdk: oraclejdk7

env:
  global:
  - secure: QKGE85X6NL+kX0a9R989zwNDouUYac8MYtkfI9BBS8teBYJBMc/QSYjAGXZPOJR/VFaXFOTDwteYA08vIGKi5ASNJunOeHkCpyYUgxUQRj/NdwGs+c0z+raeS/L5UdAmRlCeZfmPe19HNXvW95plTLf5pv3VyRsENSQJkO1yJJk=
  - secure: FdV94loU+g9w+rU5EeCQbYrxpxURvZokdWNqe/NjbfKYf7u0VaEjcVqVttTA13fkd6N31sGE1c9hXnAAQ+zSMtxr37rGDkIA3GotwDObifPs1awLoeR7kLt56U2BLyS8BkSD1HiLMxHAaJ9NUBLvqkGajzHAEQOBF4tx0rZ3jcI=

script: ./gradlew ci
```
